### ISSUE TITLE
[Crash] FragmentViewBindingDelegate edge case

### ISSUE THREAD

**Issue by kendrickkwok** [Zhuinden/fragmentviewbindingdelegate-kt#18]
Specific edge case with binding delegate -

When bindings are accessed and created lazily, when the binding is never accessed in between **onViewCreated** and **onDestroyView**, accessing the binding inside of **onDestroyView** will crash the application. It seems like when the fragment is created and abruptly destroyed - this never gives the Fragment the chance to call the binding.
Crashes with 

>  java.lang.IllegalStateException: Should not attempt to get bindings when Fragment views are destroyed.

**Comment by Zhuinden** [comment]
How did you end up in `onDestroyView` without making the binding initialized via `onViewCreated`? 🤔

**Comment by kendrickkwok** [comment]
Ah yes - we have an edge case where the binding is never used in a fragment until some conditions are met. As the activity that contains the fragment is destroyed, the fragment ends up in `onDestroyView`. Since binding is accessed and created lazily - if the conditions aren't met the fragment never gets the chance to use the binding to initialize it in the first place.

**Comment by dptsolutions** [comment]
Hi @Zhuinden, @kendrickkwok's colleague here. 

Would like to attempt to explain the issue in a little more detail, in preparation for the PR I'm about to submit to fix the issue.

Here's the conditions that were causing the crash:
1. The Fragment is created and attached to the Activity
2. Other async code runs, killing the Activity
3. The Fragment never executes any code that accesses the binding, and starts getting torn down
4. The Fragment hits `onDestroyView()`, where our cleanup code runs, becoming the first time we attempt to access the binding.

This ends up triggering the crash, because according to the [Fragment Lifecycle docs](https://developer.android.com/guide/fragments/lifecycle#fragment_created_and_view_destroyed), 

> the fragment's view Lifecycle is moved into the DESTROYED state and emits the [ON_DESTROY](https://developer.android.com/reference/androidx/lifecycle/Lifecycle.Event#ON_DESTROY) event to its observers. The fragment then invokes its [onDestroyView()](https://developer.android.com/reference/androidx/fragment/app/Fragment#onDestroyView()) callback.

Ultimately, the check `!lifecycle.currentState.isAtLeast(Lifecycle.State.INITIALIZED)` is incorrect, because the state is moved to DESTROYED before the call to `onDestroyView()`.

Our solution is to replace the lifecycle state check with `thisRef.view == null` in the `getValue()` method. That way, we can create the binding in onDestroyView safely, even though it'll be destroyed very shortly after.

We realize this is kind of dumb, but legacy code is legacy code...

**Comment by Zhuinden** [comment]
If Jitpack works, 1.0.2 should have it 

Please check if I broke anything while doing so 😅
